# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: info-T
description: 'A HPC developer blog'
email: tristan@trily.eu
url: http://info-t.trily.eu
baseurl: ""

author:
  name: 'Tristan C'
  url: http://trily.eu

paginate: 5

excerpt_separator: <!--more-->

github:
  username: tristancabel
  repo: https://github.com/tristancabel

gems:
  - jekyll-paginate
  - jekyll-gist

exclude: ['README.md', 'LICENSE']