# Site settings
title: info-T
email: your-email@domain.com
description: a HPC developer blog. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trily.eu" # the base hostname & protocol for your site
github_username:  tristancabel

# Build settings
markdown: kramdown
